version: '3'
networks:
  local:
    driver: bridge
services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      local:

    environment:
      - POSTGRES_DB=acmedb
      - POSTGRES_USER=acmedb
      - POSTGRES_PASSWORD=acmedb

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      local:

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/static:/srv/static
    ports:
      - '8088:8088'
    depends_on:
      - database
      - adminer
    networks:
      local:
